CREATE OR REPLACE TRIGGER "OCABI"."KTU_TRG_MYTABLE_I"
AFTER INSERT ON MYTABLE
FOR EACH ROW 
BEGIN
    DELETE FROM KTU_MYTABLE WHERE PK1 = :NEW.PK1;
    INSERT INTO KTU_MYTABLE (TS, STATE, PK1) VALUES (systimestamp, 'I', :NEW.PK1);
END;
--ALTER TRIGGER "OCABI"."KTU_TRG_MYTABLE_I" ENABLE;

CREATE OR REPLACE TRIGGER "OCABI"."KTU_TRG_MYTABLE_U"
AFTER UPDATE ON MYTABLE
FOR EACH ROW 
BEGIN
    DELETE FROM KTU_MYTABLE WHERE PK1 = :NEW.ID;
    INSERT INTO KTU_MYTABLE (TS, STATE, PK1) VALUES (systimestamp, 'U', :NEW.PK1);
END;
--ALTER TRIGGER "OCABI"."KTU_TRG_MYTABLE_U" ENABLE;

CREATE OR REPLACE TRIGGER "OCABI"."KTU_TRG_MYTABLE_D"
BEFORE DELETE ON MYTABLE
FOR EACH ROW 
BEGIN
    DELETE FROM KTU_MYTABLE WHERE PK1 = :OLD.ID;
    INSERT INTO KTU_MYTABLE (TS, STATE, PK1) VALUES (systimestamp, 'D', :OLD.PK1);
END;
--ALTER TRIGGER "OCABI"."KTU_TRG_MYTABLE_D" ENABLE;

select kt.TS AS LAST_MODIFIED, ot.* from ktu_mytable kt left join mytable ot on kt.PK1 = ot.PK1;

