
CREATE TABLE KTM_M2OEQUIPEMENT (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);


CREATE TABLE KTM_M2OALARME (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OHISTORIQUEDESECHANGES (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OERREUR (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OREJETSPREPAR (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OADRESSE (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OVOIE (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OCOMMUNE (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OCMDBMAJMSM (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OCMDBMAJHR (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OLIENRADIO (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_IMTICKET (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OPROJETMAINTENANCE (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OREJETMDM (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OPOINTCOMPTAGE (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OCOMPTEUR (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

CREATE TABLE KTM_M2OCONTRAT (
    KTM_TS TIMESTAMP, 
    KTM_STATE VARCHAR2(20 BYTE), 
    KTM_PK_SYSID VARCHAR2(40 BYTE),
    PRIMARY KEY (KTM_TS)
);

