DROP TRIGGER TRG_M2OEQUIPEMENT_I;
DROP TRIGGER TRG_M2OEQUIPEMENT_U;
DROP TRIGGER TRG_M2OEQUIPEMENT_D;
--------------------------------------------
DROP TRIGGER TRG_M2OALARME_I;
DROP TRIGGER TRG_M2OALARME_U;
DROP TRIGGER TRG_M2OALARME_D;
--------------------------------------------
DROP TRIGGER TRG_M2OHISTORIQUEDESECHANGES_I;
DROP TRIGGER TRG_M2OHISTORIQUEDESECHANGES_U;
DROP TRIGGER TRG_M2OHISTORIQUEDESECHANGES_D;
--------------------------------------------
DROP TRIGGER TRG_M2OERREUR_I;
DROP TRIGGER TRG_M2OERREUR_U;
DROP TRIGGER TRG_M2OERREUR_D;
--------------------------------------------
DROP TRIGGER TRG_M2OREJETSPREPAR_I;
DROP TRIGGER TRG_M2OREJETSPREPAR_U;
DROP TRIGGER TRG_M2OREJETSPREPAR_D;
--------------------------------------------
DROP TRIGGER TRG_M2OADRESSE_I;
DROP TRIGGER TRG_M2OADRESSE_U;
DROP TRIGGER TRG_M2OADRESSE_D;
--------------------------------------------
DROP TRIGGER TRG_M2OVOIE_I;
DROP TRIGGER TRG_M2OVOIE_U;
DROP TRIGGER TRG_M2OVOIE_D;
--------------------------------------------
DROP TRIGGER TRG_M2OCOMMUNE_I;
DROP TRIGGER TRG_M2OCOMMUNE_U;
DROP TRIGGER TRG_M2OCOMMUNE_D;
--------------------------------------------
DROP TRIGGER TRG_M2OCMDBMAJMSM_I;
DROP TRIGGER TRG_M2OCMDBMAJMSM_U;
DROP TRIGGER TRG_M2OCMDBMAJMSM_D;
--------------------------------------------
DROP TRIGGER TRG_M2OCMDBMAJHR_I;
DROP TRIGGER TRG_M2OCMDBMAJHR_U;
DROP TRIGGER TRG_M2OCMDBMAJHR_D;
--------------------------------------------
DROP TRIGGER TRG_M2OLIENRADIO_I;
DROP TRIGGER TRG_M2OLIENRADIO_U;
DROP TRIGGER TRG_M2OLIENRADIO_D;
--------------------------------------------
DROP TRIGGER TRG_IMTICKET_I;
DROP TRIGGER TRG_IMTICKET_U;
DROP TRIGGER TRG_IMTICKET_D;
--------------------------------------------
DROP TRIGGER TRG_M2OPROJETMAINTENANCE_I;
DROP TRIGGER TRG_M2OPROJETMAINTENANCE_U;
DROP TRIGGER TRG_M2OPROJETMAINTENANCE_D;
--------------------------------------------
DROP TRIGGER TRG_M2OREJETMDM_I;
DROP TRIGGER TRG_M2OREJETMDM_U;
DROP TRIGGER TRG_M2OREJETMDM_D;
--------------------------------------------
DROP TRIGGER TRG_M2OPOINTCOMPTAGE_I;
DROP TRIGGER TRG_M2OPOINTCOMPTAGE_U;
DROP TRIGGER TRG_M2OPOINTCOMPTAGE_D;
--------------------------------------------
DROP TRIGGER TRG_M2OCOMPTEUR_I;
DROP TRIGGER TRG_M2OCOMPTEUR_U;
DROP TRIGGER TRG_M2OCOMPTEUR_D;
--------------------------------------------
DROP TRIGGER TRG_M2OCONTRAT_I;
DROP TRIGGER TRG_M2OCONTRAT_U;
DROP TRIGGER TRG_M2OCONTRAT_D;

